name: build, test and run

on:
  workflow_dispatch:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    steps:

      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: set environment variables
        run: |
          touch .env
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
          echo "TURSO_URL=${{ secrets.TURSO_URL }}" >> .env
          echo "TURSO_TOKEN=${{ secrets.TURSO_TOKEN }}" >> .env

      - name: install dependencies, build and test
        run: |
          bun install
          bun run test
          bun run build:arm

      - uses: actions/upload-artifact@v2
        with:
          name: executor
          path: lib/executor_arm64
          if-no-files-found: error
  
  run:
    name: run
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: executor
      
      - name: move to $HOME/apps
        run: mv executor_arm64 $HOME/apps/executor_arm64
      
      - name: run executor
        run: |
          chmod +x $HOME/apps/executor_arm64
          $HOME/apps/executor_arm64 &