name: Makefile CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        chmod +x config/build
        chmod +x config/configure
        source /home/$(user)/.bashrc
        ./config/configure
        ./config/build